### ISSUE TITLE
How to run on heroku?

### ISSUE THREAD

**Issue by J0113** [ahung89/bomb-arena#5]
I saw that you put this on heroku and I was wondering if you could make a "Deploy to heroku button". I want to try to add a new map!

**Comment by Stoakes** [comment]
Hello,

I'm not the project owner, but you've got the [Procfile](https://github.com/ahung89/bomb-arena/blob/master/Procfile) in the repository. 
So it should work easily on Heroku. Just push the code to Heroku and should work

**Comment by J0113** [comment]
I've got it to work already!

I've edited the code a little bit and now you can easilly deploy it to heroku via my repo:
https://github.com/jollesnaas/Bomb-Arena

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/jollesnaas/Bomb-Arena/tree/master)
